// https://github.com/ajaxorg/ace/issues/1287
export default {
	// "Alt-Left": "goSubwordLeft",
	// "Alt-Right": "goSubwordRight",
	// "Ctrl-Up": "scrollLineUp",
	// "Ctrl-Down": "scrollLineDown",
	"Shift-Ctrl-L": "splitSelectionByLine",
	"Shift-Tab": "indentLess",
	"Esc": "singleSelectionTop",
	"Cmd-L": "expandtoline",
	"Shift-Ctrl-K": "deleteLine",
	"Cmd-Enter": "insertLineAfter",
	"Shift-Cmd-Enter": "insertLineBefore",
	"Cmd-D": "selectNextOccurrence",
	// "Shift-Ctrl-Space": "selectScope",
	"Shift-Ctrl-M": "selectBetweenBrackets",
	"Ctrl-M": "goToBracket",
	"Cmd-Ctrl-Up": "swapLineUp",
	"Cmd-Ctrl-Down": "swapLineDown",
	"Ctrl-/": "toggleComment",
	"Ctrl-J": "joinLines",
	"Shift-Cmd-D": "duplicateLine",
	"Ctrl-T": "transposeChars",
	// "F9": "sortLines",
	// "Ctrl-F9": "sortLinesInsensitive",
	"F2": "nextBookmark",
	"Shift-F2": "prevBookmark",
	"Cmd-F2": "toggleBookmark",
	"Shift-Cmd-F2": "clearBookmarks",
	// "Alt-F2": "selectBookmarks",
	// "Alt-Q": "wrapLines",
	"Cmd-K Cmd-Backspace": "delLineLeft",
	"Cmd-K Cmd-K": "delLineRight",
	"Cmd-K Cmd-U": "upcaseAtCursor",
	"Cmd-K Cmd-L": "downcaseAtCursor",
	// "Cmd-K Cmd-Space": "setSublimeMark",
	// "Cmd-K Cmd-A": "selectToSublimeMark",
	// "Cmd-K Cmd-W": "deleteToSublimeMark",
	// "Cmd-K Cmd-X": "swapWithSublimeMark",
	// "Cmd-K Cmd-Y": "sublimeYank",
	// "Cmd-K Cmd-G": "clearBookmarks",
	// "Cmd-K Cmd-C": "showInCenter",
	"Shift-Alt-Up": "selectLinesUpward",
	"Shift-Alt-Down": "selectLinesDownward",
	// "Ctrl-F3": "findUnder",
	// "Shift-Ctrl-F3": "findUnderPrevious",
	// "Shift-Ctrl-[": "fold",
	// "Shift-Ctrl-]": "unfold",
	"Ctrl-K Ctrl-j": "unfoldAll",
	"Ctrl-K Ctrl-0": "unfoldAll",
	// "Ctrl-H": "replace",
}
